### ISSUE TITLE
Runtime.shutdown() not working correctly.

### ISSUE THREAD

**Issue by gskip17** [periscope-ps/UNISrt#29] opened 2018-07-11 14:58 UTC
Basic Runtime Usage keeps the RT going even after program end.

rt.shutdown() appears to not be working.

just an annoyance, wanted to get the issue up here.

**Comment by jemusser** [comment] 2019-01-28 16:00
Unable to reproduce, tentatively closing this issue.

**Closed as completed by jemusser** 2019-01-28 16:00 UTC
Labels: bug
